import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { 
  UserPlus, 
  Mail, 
  Phone, 
  User, 
  Briefcase, 
  Copy, 
  Check, 
  Send,
  Shield,
  Users,
  GraduationCap,
  Sparkles,
  Key,
  MessageSquare,
  Eye,
  EyeOff
} from "lucide-react";
import { toast } from "sonner";
import { cn } from "@/lib/utils";
import { useAuthStore } from "@/lib/auth-store";
import { useCreateTeamMember } from "@/hooks/useTeamMembers";
import { useCreateTeacher } from "@/hooks/useTeachers";
import { useCreateChat, useSendMessage } from "@/hooks/useChats";
import { useNavigate } from "react-router-dom";

type UserType = "sales_team" | "team_leader" | "teacher";

interface UserFormData {
  name: string;
  email: string;
  phone: string;
  userType: UserType | "";
}

interface GeneratedCredentials {
  userId: string;
  password: string;
}

const userTypeConfig = {
  sales_team: { 
    label: "Sales Manager", 
    icon: Briefcase, 
    color: "from-blue-500 to-blue-600",
    bgColor: "bg-blue-500/10",
    textColor: "text-blue-500"
  },
  team_leader: { 
    label: "Team Leader", 
    icon: Users, 
    color: "from-purple-500 to-purple-600",
    bgColor: "bg-purple-500/10",
    textColor: "text-purple-500"
  },
  teacher: { 
    label: "Teacher", 
    icon: GraduationCap, 
    color: "from-emerald-500 to-emerald-600",
    bgColor: "bg-emerald-500/10",
    textColor: "text-emerald-500"
  },
};

const generateUserId = (userType: UserType, name: string): string => {
  const prefix = {
    sales_team: "SM",
    team_leader: "TL",
    teacher: "TR"
  }[userType];
  const randomNum = Math.floor(1000 + Math.random() * 9000);
  const initials = name.split(" ").map(n => n[0]).join("").toUpperCase().slice(0, 2);
  return `${prefix}-${initials}-${randomNum}`;
};

const generatePassword = (): string => {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789";
  const specialChars = "@#$%&*!";
  let password = "";
  for (let i = 0; i < 8; i++) {
    password += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  password += specialChars.charAt(Math.floor(Math.random() * specialChars.length));
  password += Math.floor(10 + Math.random() * 90);
  return password;
};

export function CreateUserDialog() {
  const [open, setOpen] = useState(false);
  const [step, setStep] = useState<"form" | "credentials" | "sending">("form");
  const createTeamMember = useCreateTeamMember();
  const createTeacher = useCreateTeacher();
  const createChatMutation = useCreateChat();
  const sendMessageMutation = useSendMessage();
  const { currentUser } = useAuthStore();
  const navigate = useNavigate();
  const [formData, setFormData] = useState<UserFormData>({
    name: "",
    email: "",
    phone: "",
    userType: "",
  });
  const [credentials, setCredentials] = useState<GeneratedCredentials | null>(null);
  const [showPassword, setShowPassword] = useState(false);
  const [copiedField, setCopiedField] = useState<"userId" | "password" | null>(null);
  const [sendingProgress, setSendingProgress] = useState({ email: false, sms: false });
  const [sentStatus, setSentStatus] = useState({ email: false, sms: false });

  const handleInputChange = (field: keyof UserFormData, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  const validateForm = (): boolean => {
    if (!formData.name.trim()) {
      toast.error("Please enter the user's name");
      return false;
    }
    if (!formData.email.trim() || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.email)) {
      toast.error("Please enter a valid email address");
      return false;
    }
    if (!formData.phone.trim()) {
      toast.error("Please enter a phone number");
      return false;
    }
    if (!formData.userType) {
      toast.error("Please select a user type");
      return false;
    }
    // Password is auto-generated, no validation needed
    return true;
  };

  const handleCreateUser = () => {
    if (!validateForm()) return;
    
    const userData = {
      name: formData.name,
      email: formData.email,
      phone: formData.phone,
      role: formData.userType,
      password: '', // Password will be auto-generated by backend
      status: 'active',
      joinedAt: new Date().toISOString().split('T')[0],
      rating: 4.5,
      performance: 85,
      targetProgress: 50,
    };
    
    // Create via backend API (will generate credentials and send email)
    if (formData.userType === 'sales_team' || formData.userType === 'team_leader') {
      createTeamMember.mutate(userData as any, {
        onSuccess: (response: any) => {
          const generatedPassword = response.plainPassword || generatePassword();
          setCredentials({ 
            userId: formData.email, 
            password: generatedPassword 
          });
          setStep("credentials");
          if (response.emailSent) {
            setSentStatus({ email: true, sms: false });
          }
          
          // Add user to auth store for login
          const { addUser } = useAuthStore.getState();
          const newUser = {
            id: response._id || response.id,
            name: formData.name,
            email: formData.email,
            phone: formData.phone,
            role: formData.userType as any,
            createdAt: new Date().toISOString().split('T')[0],
            ...(formData.userType === 'sales_team' ? { assignedLeads: [] } : {}),
            ...(formData.userType === 'team_leader' ? { teachersManaged: [] } : {}),
          };
          addUser(newUser, generatedPassword);
          
          // Create chat with credentials
          setTimeout(() => {
            handleCreateCredentialsChat(response._id || response.id, response);
          }, 500);
          
          // Close dialog after showing credentials
          setTimeout(() => {
            handleClose();
          }, 3000);
        }
      });
    } else if (formData.userType === 'teacher') {
      createTeacher.mutate({
        name: formData.name,
        email: formData.email,
        phone: formData.phone,
        title: 'Teacher',
        specialization: [],
        students: 0,
        rating: 4.5,
        classesToday: 0,
        classesCompleted: 0,
        status: 'available',
        joinedAt: new Date().toISOString().split('T')[0],
        performance: 85,
      } as any, {
        onSuccess: (response: any) => {
          const generatedPassword = response.plainPassword || generatePassword();
          setCredentials({ 
            userId: formData.email, 
            password: generatedPassword 
          });
          setStep("credentials");
          if (response.emailSent) {
            setSentStatus({ email: true, sms: false });
          }
          
          // Add user to auth store for login
          const { addUser } = useAuthStore.getState();
          const newUser = {
            id: response._id || response.id,
            name: formData.name,
            email: formData.email,
            phone: formData.phone,
            role: formData.userType as any,
            createdAt: new Date().toISOString().split('T')[0],
            teacherId: response._id || response.id,
          };
          addUser(newUser, generatedPassword);
          
          // Create chat with credentials
          setTimeout(() => {
            handleCreateCredentialsChat(response._id || response.id, response);
          }, 500);
          
          // Close dialog after showing credentials
          setTimeout(() => {
            handleClose();
          }, 3000);
        }
      });
    }
  };

  const handleCopy = async (field: "userId" | "password") => {
    if (!credentials) return;
    const value = field === "userId" ? credentials.userId : credentials.password;
    await navigator.clipboard.writeText(value);
    setCopiedField(field);
    toast.success(`${field === "userId" ? "User ID" : "Password"} copied to clipboard`);
    setTimeout(() => setCopiedField(null), 2000);
  };

  const handleSendCredentials = async () => {
    setStep("sending");
    
    // Simulate sending email
    setSendingProgress({ email: true, sms: false });
    await new Promise(resolve => setTimeout(resolve, 1500));
    setSentStatus(prev => ({ ...prev, email: true }));
    setSendingProgress({ email: false, sms: true });
    
    // Simulate sending SMS
    await new Promise(resolve => setTimeout(resolve, 1200));
    setSentStatus(prev => ({ ...prev, sms: true }));
    setSendingProgress({ email: false, sms: false });
    
    toast.success("Credentials sent successfully!", {
      description: `Login details sent to ${formData.email} and ${formData.phone}`
    });
    
    // Auto close after short delay
    setTimeout(() => {
      handleClose();
    }, 1500);
  };

  const handleCreateCredentialsChat = async (memberId: string, memberData: any) => {
    if (!currentUser) return;
    
    // Determine chat type based on role
    const determineChatType = (role: string) => {
      if (role === 'sales_team' || role === 'team_leader') return 'admin_view';
      if (role === 'teacher') return 'admin_view';
      return 'admin_view';
    };
    
    // Create chat with the new member
    createChatMutation.mutate({
      participants: [
        { 
          userId: currentUser.id || (currentUser as any).userId || '', 
          userModel: 'User', 
          name: currentUser.name, 
          role: 'admin' 
        },
        { 
          userId: memberId, 
          userModel: formData.userType === 'teacher' ? 'Teacher' : 'TeamMember', 
          name: formData.name, 
          role: formData.userType as any 
        },
      ],
      chatType: determineChatType(formData.userType),
    }, {
      onSuccess: (newChat) => {
        // Send credentials message in the chat
        const credentialsMessage = `🌙 Assalamu Alaikum, ${formData.name}!\n\n✨ Welcome to Quran Academy CRM ✨\n\nYour account has been successfully created and activated. We're excited to have you on board!\n\n╔═══════════════════════════════════════╗\n║        YOUR LOGIN CREDENTIALS         ║\n╚═══════════════════════════════════════╝\n\n👤 Name: ${formData.name}\n📧 Email: ${formData.email}\n🔐 Password: ${credentials?.password || 'Auto-generated'}\n🌐 Portal: ${window.location.origin}\n\n╔═══════════════════════════════════════╗\n║         GETTING STARTED               ║\n╚═══════════════════════════════════════╝\n\n1️⃣ Visit the login portal using the URL above\n2️⃣ Enter your email and password\n3️⃣ Explore your personalized dashboard\n4️⃣ Start managing your tasks and activities\n\n╔═══════════════════════════════════════╗\n║       SECURITY REMINDER               ║\n╚═══════════════════════════════════════╝\n\n🔒 Keep your credentials confidential\n🚫 Never share your password with anyone\n✅ Always logout after your session\n\n💬 Need Help?\nIf you have any questions or need assistance, feel free to reach out to your administrator anytime.\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\nBest regards,\n🕌 Quran Academy CRM Team\n\nJazakAllah Khair! 🤲`;
        
        sendMessageMutation.mutate({
          chatId: newChat._id,
          content: credentialsMessage,
          senderId: currentUser.id || (currentUser as any).userId || '',
          senderModel: 'User',
          senderName: currentUser.name,
          senderRole: 'admin',
        });
        
        toast.success('Chat created with credentials!', {
          description: 'Credentials have been sent in chat',
          action: {
            label: 'View Chat',
            onClick: () => navigate(`/messages?userId=${memberId}&userName=${encodeURIComponent(formData.name)}&userRole=${formData.userType}`),
          },
        });
      },
    });
  };

  const handleClose = () => {
    setOpen(false);
    setTimeout(() => {
      setStep("form");
      setFormData({ name: "", email: "", phone: "", userType: "" });
      setCredentials(null);
      setSendingProgress({ email: false, sms: false });
      setSentStatus({ email: false, sms: false });
      setShowPassword(false);
    }, 200);
  };

  const selectedConfig = formData.userType ? userTypeConfig[formData.userType as UserType] : null;

  return (
    <Dialog open={open} onOpenChange={(isOpen) => isOpen ? setOpen(true) : handleClose()}>
      <DialogTrigger asChild>
        <Button className="gap-2 bg-gradient-to-r from-primary to-primary/80 hover:from-primary/90 hover:to-primary/70">
          <UserPlus className="h-4 w-4" />
          Create Team Member
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-3">
            <div className={cn(
              "h-10 w-10 rounded-xl flex items-center justify-center",
              step === "sending" 
                ? "bg-info/20"
                : step === "credentials" 
                  ? "bg-success/20" 
                  : selectedConfig 
                    ? selectedConfig.bgColor 
                    : "bg-primary/10"
            )}>
              {step === "sending" ? (
                <Send className="h-5 w-5 text-info animate-pulse" />
              ) : step === "credentials" ? (
                <Key className="h-5 w-5 text-success" />
              ) : selectedConfig ? (
                <selectedConfig.icon className={cn("h-5 w-5", selectedConfig.textColor)} />
              ) : (
                <UserPlus className="h-5 w-5 text-primary" />
              )}
            </div>
            <div>
              <span>
                {step === "sending" 
                  ? "Sending Credentials" 
                  : step === "credentials" 
                    ? "Credentials Generated" 
                    : "Create Team Member"
                }
              </span>
              <p className="text-sm text-muted-foreground font-normal">
                {step === "sending"
                  ? "Delivering login details to user"
                  : step === "credentials" 
                    ? "Share these credentials with the user" 
                    : "Add a new team member to the system"
                }
              </p>
            </div>
          </DialogTitle>
        </DialogHeader>

        {step === "form" ? (
          <div className="space-y-5 pt-4">
            {/* User Type Selection */}
            <div className="space-y-3">
              <Label className="text-sm font-medium">Select User Type</Label>
              <div className="grid grid-cols-3 gap-3">
                {(Object.entries(userTypeConfig) as [UserType, typeof userTypeConfig[UserType]][]).map(([type, config]) => {
                  const Icon = config.icon;
                  const isSelected = formData.userType === type;
                  
                  return (
                    <button
                      key={type}
                      type="button"
                      onClick={() => handleInputChange("userType", type)}
                      className={cn(
                        "p-4 rounded-xl border-2 transition-all flex flex-col items-center gap-2 hover:shadow-md",
                        isSelected 
                          ? `border-${type === 'sales_team' ? 'blue' : type === 'team_leader' ? 'purple' : 'emerald'}-500 bg-gradient-to-br ${config.bgColor}` 
                          : "border-border hover:border-muted-foreground/30"
                      )}
                    >
                      <div className={cn(
                        "h-10 w-10 rounded-xl flex items-center justify-center transition-all",
                        isSelected ? `bg-gradient-to-br ${config.color}` : config.bgColor
                      )}>
                        <Icon className={cn("h-5 w-5", isSelected ? "text-white" : config.textColor)} />
                      </div>
                      <span className={cn(
                        "text-xs font-medium",
                        isSelected ? config.textColor : "text-muted-foreground"
                      )}>
                        {config.label}
                      </span>
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Form Fields */}
            <div className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="name" className="flex items-center gap-2">
                  <User className="h-4 w-4 text-muted-foreground" />
                  Full Name
                </Label>
                <Input
                  id="name"
                  placeholder="Enter full name"
                  value={formData.name}
                  onChange={(e) => handleInputChange("name", e.target.value)}
                />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="email" className="flex items-center gap-2">
                  <Mail className="h-4 w-4 text-muted-foreground" />
                  Email Address
                </Label>
                <Input
                  id="email"
                  type="email"
                  placeholder="Enter email address"
                  value={formData.email}
                  onChange={(e) => handleInputChange("email", e.target.value)}
                />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="phone" className="flex items-center gap-2">
                  <Phone className="h-4 w-4 text-muted-foreground" />
                  Phone Number
                </Label>
                <Input
                  id="phone"
                  placeholder="Enter phone number"
                  value={formData.phone}
                  onChange={(e) => handleInputChange("phone", e.target.value)}
                />
              </div>
            </div>

            <Button 
              className="w-full gap-2 bg-gradient-to-r from-primary to-primary/80"
              onClick={handleCreateUser}
              disabled={!formData.userType}
            >
              <UserPlus className="h-4 w-4" />
              Create User
            </Button>
          </div>
        ) : step === "credentials" ? (
          <div className="space-y-5 pt-4">
            {/* User Info Summary */}
            <div className="p-4 rounded-xl bg-muted/50 border">
              <div className="flex items-center gap-3">
                <div className="h-12 w-12 rounded-full bg-gradient-to-br from-primary to-primary/80 flex items-center justify-center text-primary-foreground font-bold text-lg">
                  {formData.name.split(" ").map(n => n[0]).join("").slice(0, 2)}
                </div>
                <div>
                  <p className="font-semibold">{formData.name}</p>
                  <div className="flex items-center gap-2">
                    {selectedConfig && (
                      <Badge className={cn("text-xs", selectedConfig.bgColor, selectedConfig.textColor)}>
                        {selectedConfig.label}
                      </Badge>
                    )}
                  </div>
                </div>
              </div>
              <div className="mt-3 pt-3 border-t grid grid-cols-2 gap-2 text-sm">
                <div className="flex items-center gap-2 text-muted-foreground">
                  <Mail className="h-3 w-3" />
                  <span className="truncate">{formData.email}</span>
                </div>
                <div className="flex items-center gap-2 text-muted-foreground">
                  <Phone className="h-3 w-3" />
                  <span>{formData.phone}</span>
                </div>
              </div>
            </div>

            {/* Generated Credentials */}
            <div className="space-y-3">
              <div className="p-4 rounded-xl bg-gradient-to-br from-success/10 to-success/5 border border-success/20">
                <div className="flex items-center justify-between mb-2">
                  <Label className="text-sm text-muted-foreground">Login Email</Label>
                  <Button
                    variant="ghost"
                    size="sm"
                    className="h-8 gap-1 text-xs"
                    onClick={() => handleCopy("userId")}
                  >
                    {copiedField === "userId" ? (
                      <>
                        <Check className="h-3 w-3 text-success" />
                        Copied
                      </>
                    ) : (
                      <>
                        <Copy className="h-3 w-3" />
                        Copy
                      </>
                    )}
                  </Button>
                </div>
                <p className="font-mono text-lg font-bold text-success break-all">{credentials?.userId}</p>
              </div>
              
              <div className="p-4 rounded-xl bg-gradient-to-br from-primary/10 to-primary/5 border border-primary/20">
                <div className="flex items-center justify-between mb-2">
                  <Label className="text-sm text-muted-foreground">Password</Label>
                  <Button
                    variant="ghost"
                    size="sm"
                    className="h-8 gap-1 text-xs"
                    onClick={() => handleCopy("password")}
                  >
                    {copiedField === "password" ? (
                      <>
                        <Check className="h-3 w-3 text-success" />
                        Copied
                      </>
                    ) : (
                      <>
                        <Copy className="h-3 w-3" />
                        Copy
                      </>
                    )}
                  </Button>
                </div>
                <p className="font-mono text-lg font-bold text-primary">{credentials?.password}</p>
              </div>
            </div>

            {/* Action Buttons */}
            <div className="flex gap-3">
              <Button 
                variant="outline"
                className="flex-1 gap-2"
                onClick={handleSendCredentials}
              >
                <Send className="h-4 w-4" />
                Send to User
              </Button>
              <Button 
                className="flex-1 gap-2 bg-gradient-to-r from-success to-emerald-500"
                onClick={handleClose}
              >
                <Check className="h-4 w-4" />
                Done
              </Button>
            </div>

            <p className="text-xs text-center text-muted-foreground">
              Credentials will be sent to the provided email and phone number
            </p>
          </div>
        ) : step === "sending" ? (
          <div className="space-y-5 pt-4">
            {/* Sending Animation */}
            <div className="py-8 text-center">
              <div className="w-20 h-20 mx-auto rounded-full bg-gradient-to-br from-info/20 to-info/10 flex items-center justify-center mb-6">
                <Send className="h-10 w-10 text-info animate-bounce" />
              </div>
              <h3 className="text-lg font-semibold mb-2">Sending Credentials</h3>
              <p className="text-sm text-muted-foreground mb-6">
                Delivering login details to {formData.name}
              </p>
              
              {/* Progress indicators */}
              <div className="space-y-4 max-w-xs mx-auto">
                <div className={cn(
                  "flex items-center gap-3 p-3 rounded-lg transition-all",
                  sentStatus.email ? "bg-success/10" : sendingProgress.email ? "bg-info/10" : "bg-muted/50"
                )}>
                  <div className={cn(
                    "h-10 w-10 rounded-full flex items-center justify-center transition-all",
                    sentStatus.email ? "bg-success text-success-foreground" : sendingProgress.email ? "bg-info text-info-foreground animate-pulse" : "bg-muted"
                  )}>
                    {sentStatus.email ? <Check className="h-5 w-5" /> : <Mail className="h-5 w-5" />}
                  </div>
                  <div className="flex-1 text-left">
                    <p className="font-medium text-sm">Email</p>
                    <p className="text-xs text-muted-foreground truncate">{formData.email}</p>
                  </div>
                  {sendingProgress.email && (
                    <div className="h-4 w-4 border-2 border-info border-t-transparent rounded-full animate-spin" />
                  )}
                  {sentStatus.email && (
                    <Badge variant="default" className="bg-success text-success-foreground">Sent</Badge>
                  )}
                </div>
                
                <div className={cn(
                  "flex items-center gap-3 p-3 rounded-lg transition-all",
                  sentStatus.sms ? "bg-success/10" : sendingProgress.sms ? "bg-info/10" : "bg-muted/50"
                )}>
                  <div className={cn(
                    "h-10 w-10 rounded-full flex items-center justify-center transition-all",
                    sentStatus.sms ? "bg-success text-success-foreground" : sendingProgress.sms ? "bg-info text-info-foreground animate-pulse" : "bg-muted"
                  )}>
                    {sentStatus.sms ? <Check className="h-5 w-5" /> : <MessageSquare className="h-5 w-5" />}
                  </div>
                  <div className="flex-1 text-left">
                    <p className="font-medium text-sm">SMS</p>
                    <p className="text-xs text-muted-foreground">{formData.phone}</p>
                  </div>
                  {sendingProgress.sms && (
                    <div className="h-4 w-4 border-2 border-info border-t-transparent rounded-full animate-spin" />
                  )}
                  {sentStatus.sms && (
                    <Badge variant="default" className="bg-success text-success-foreground">Sent</Badge>
                  )}
                </div>
              </div>
            </div>
          </div>
        ) : null}
      </DialogContent>
    </Dialog>
  );
}
