// Country to Currency Mapping
// Maps countries to their default currencies for automatic detection

const countryCurrencyMap = {
  // Pakistan
  'Pakistan': 'PKR',
  'PK': 'PKR',
  
  // United Kingdom
  'United Kingdom': 'GBP',
  'UK': 'GBP',
  'GB': 'GBP',
  'England': 'GBP',
  'Scotland': 'GBP',
  'Wales': 'GBP',
  'Northern Ireland': 'GBP',
  
  // United States
  'United States': 'USD',
  'USA': 'USD',
  'US': 'USD',
  'America': 'USD',
  
  // Canada
  'Canada': 'CAD',
  'CA': 'CAD',
  
  // Australia
  'Australia': 'AUD',
  'AU': 'AUD',
  
  // United Arab Emirates
  'United Arab Emirates': 'AED',
  'UAE': 'AED',
  'Dubai': 'AED',
  'Abu Dhabi': 'AED',
  'AE': 'AED',
  
  // Saudi Arabia
  'Saudi Arabia': 'SAR',
  'KSA': 'SAR',
  'SA': 'SAR',
  
  // Germany
  'Germany': 'EUR',
  'DE': 'EUR',
  
  // Other European countries using EUR
  'France': 'EUR',
  'FR': 'EUR',
  'Italy': 'EUR',
  'IT': 'EUR',
  'Spain': 'EUR',
  'ES': 'EUR',
  'Netherlands': 'EUR',
  'NL': 'EUR',
  'Belgium': 'EUR',
  'BE': 'EUR',
  'Austria': 'EUR',
  'AT': 'EUR',
  'Ireland': 'EUR',
  'IE': 'EUR',
  'Portugal': 'EUR',
  'PT': 'EUR',
  'Greece': 'EUR',
  'GR': 'EUR',
  'Finland': 'EUR',
  'FI': 'EUR',
  
  // Other countries
  'India': 'INR',
  'IN': 'INR',
  'Bangladesh': 'BDT',
  'BD': 'BDT',
  'Malaysia': 'MYR',
  'MY': 'MYR',
  'Singapore': 'SGD',
  'SG': 'SGD',
  'New Zealand': 'NZD',
  'NZ': 'NZD',
  'South Africa': 'ZAR',
  'ZA': 'ZAR',
  'Nigeria': 'NGN',
  'NG': 'NGN',
  'Egypt': 'EGP',
  'EG': 'EGP',
  'Turkey': 'TRY',
  'TR': 'TRY',
  'Indonesia': 'IDR',
  'ID': 'IDR',
  'Philippines': 'PHP',
  'PH': 'PHP',
  'Thailand': 'THB',
  'TH': 'THB',
  'Vietnam': 'VND',
  'VN': 'VND',
  'Japan': 'JPY',
  'JP': 'JPY',
  'China': 'CNY',
  'CN': 'CNY',
  'Hong Kong': 'HKD',
  'HK': 'HKD',
  'South Korea': 'KRW',
  'KR': 'KRW',
  'Mexico': 'MXN',
  'MX': 'MXN',
  'Brazil': 'BRL',
  'BR': 'BRL',
  'Argentina': 'ARS',
  'AR': 'ARS',
  'Colombia': 'COP',
  'CO': 'COP',
  'Chile': 'CLP',
  'CL': 'CLP',
  'Peru': 'PEN',
  'PE': 'PEN',
  'Russia': 'RUB',
  'RU': 'RUB',
  'Switzerland': 'CHF',
  'CH': 'CHF',
  'Sweden': 'SEK',
  'SE': 'SEK',
  'Norway': 'NOK',
  'NO': 'NOK',
  'Denmark': 'DKK',
  'DK': 'DKK',
  'Poland': 'PLN',
  'PL': 'PLN',
  'Czech Republic': 'CZK',
  'CZ': 'CZK',
  'Hungary': 'HUF',
  'HU': 'HUF',
  'Romania': 'RON',
  'RO': 'RON',
  'Bulgaria': 'BGN',
  'BG': 'BGN',
  'Croatia': 'EUR',
  'HR': 'EUR',
  'Slovenia': 'EUR',
  'SI': 'EUR',
  'Slovakia': 'EUR',
  'SK': 'EUR',
  'Estonia': 'EUR',
  'EE': 'EUR',
  'Latvia': 'EUR',
  'LV': 'EUR',
  'Lithuania': 'EUR',
  'LT': 'EUR',
  'Cyprus': 'EUR',
  'CY': 'EUR',
  'Malta': 'EUR',
  'MT': 'EUR',
  'Luxembourg': 'EUR',
  'LU': 'EUR',
  'Iceland': 'ISK',
  'IS': 'ISK',
  'Israel': 'ILS',
  'IL': 'ILS',
  'Jordan': 'JOD',
  'JO': 'JOD',
  'Lebanon': 'LBP',
  'LB': 'LBP',
  'Kuwait': 'KWD',
  'KW': 'KWD',
  'Qatar': 'QAR',
  'QA': 'QAR',
  'Bahrain': 'BHD',
  'BH': 'BHD',
  'Oman': 'OMR',
  'OM': 'OMR',
  'Morocco': 'MAD',
  'MA': 'MAD',
  'Tunisia': 'TND',
  'TN': 'TND',
  'Algeria': 'DZD',
  'DZ': 'DZD',
  'Libya': 'LYD',
  'LY': 'LYD',
  'Kenya': 'KES',
  'KE': 'KES',
  'Ghana': 'GHS',
  'GH': 'GHS',
  'Uganda': 'UGX',
  'UG': 'UGX',
  'Tanzania': 'TZS',
  'TZ': 'TZS',
  'Ethiopia': 'ETB',
  'ET': 'ETB',
  'Sri Lanka': 'LKR',
  'LK': 'LKR',
  'Nepal': 'NPR',
  'NP': 'NPR',
  'Myanmar': 'MMK',
  'MM': 'MMK',
  'Cambodia': 'KHR',
  'KH': 'KHR',
  'Laos': 'LAK',
  'LA': 'LAK',
  'Brunei': 'BND',
  'BN': 'BND',
  'Pakistan': 'PKR',
  'Afghanistan': 'AFN',
  'AF': 'AFN',
  'Iran': 'IRR',
  'IR': 'IRR',
  'Iraq': 'IQD',
  'IQ': 'IQD',
  'Syria': 'SYP',
  'SY': 'SYP',
  'Yemen': 'YER',
  'YE': 'YER',
  'Sudan': 'SDG',
  'SD': 'SDG',
  'South Sudan': 'SSP',
  'SS': 'SSP',
  'Somalia': 'SOS',
  'SO': 'SOS',
  'Djibouti': 'DJF',
  'DJ': 'DJF',
  'Eritrea': 'ERN',
  'ER': 'ERN',
  'Mauritius': 'MUR',
  'MU': 'MUR',
  'Seychelles': 'SCR',
  'SC': 'SCR',
  'Rwanda': 'RWF',
  'RW': 'RWF',
  'Burundi': 'BIF',
  'BI': 'BIF',
  'Democratic Republic of Congo': 'CDF',
  'DRC': 'CDF',
  'Congo': 'CDF',
  'CG': 'CDF',
  'Gabon': 'XAF',
  'GA': 'XAF',
  'Cameroon': 'XAF',
  'CM': 'XAF',
  'Central African Republic': 'XAF',
  'CAR': 'XAF',
  'Chad': 'XAF',
  'TD': 'XAF',
  'Equatorial Guinea': 'XAF',
  'GQ': 'XAF',
  'Republic of Congo': 'XAF',
  'Benin': 'XOF',
  'BJ': 'XOF',
  'Burkina Faso': 'XOF',
  'BF': 'XOF',
  'Ivory Coast': 'XOF',
  'CI': 'XOF',
  'Guinea-Bissau': 'XOF',
  'GW': 'XOF',
  'Mali': 'XOF',
  'ML': 'XOF',
  'Niger': 'XOF',
  'NE': 'XOF',
  'Senegal': 'XOF',
  'SN': 'XOF',
  'Togo': 'XOF',
  'TG': 'XOF',
  'Angola': 'AOA',
  'AO': 'AOA',
  'Mozambique': 'MZN',
  'MZ': 'MZN',
  'Zambia': 'ZMW',
  'ZM': 'ZMW',
  'Zimbabwe': 'ZWL',
  'ZW': 'ZWL',
  'Botswana': 'BWP',
  'BW': 'BWP',
  'Namibia': 'NAD',
  'NA': 'NAD',
  'Lesotho': 'LSL',
  'LS': 'LSL',
  'Eswatini': 'SZL',
  'SZ': 'SZL',
  'Malawi': 'MWK',
  'MW': 'MWK',
  'Madagascar': 'MGA',
  'MG': 'MGA',
  'Comoros': 'KMF',
  'KM': 'KMF',
  'Macedonia': 'MKD',
  'MK': 'MKD',
  'Serbia': 'RSD',
  'RS': 'RSD',
  'Montenegro': 'EUR',
  'ME': 'EUR',
  'Kosovo': 'EUR',
  'XK': 'EUR',
  'Bosnia and Herzegovina': 'BAM',
  'BA': 'BAM',
  'Albania': 'ALL',
  'AL': 'ALL',
  'Moldova': 'MDL',
  'MD': 'MDL',
  'Ukraine': 'UAH',
  'UA': 'UAH',
  'Belarus': 'BYN',
  'BY': 'BYN',
  'Kazakhstan': 'KZT',
  'KZ': 'KZT',
  'Uzbekistan': 'UZS',
  'UZ': 'UZS',
  'Turkmenistan': 'TMT',
  'TM': 'TMT',
  'Tajikistan': 'TJS',
  'TJ': 'TJS',
  'Kyrgyzstan': 'KGS',
  'KG': 'KGS',
  'Armenia': 'AMD',
  'AM': 'AMD',
  'Georgia': 'GEL',
  'GE': 'GEL',
  'Azerbaijan': 'AZN',
  'AZ': 'AZN',
  'Mongolia': 'MNT',
  'MN': 'MNT',
  'North Korea': 'KPW',
  'KP': 'KPW',
  'Taiwan': 'TWD',
  'TW': 'TWD',
  'Macau': 'MOP',
  'MO': 'MOP',
  'Hong Kong': 'HKD',
  'HK': 'HKD',
  'Brunei': 'BND',
  'BN': 'BND',
  'East Timor': 'USD',
  'TL': 'USD',
  'Papua New Guinea': 'PGK',
  'PG': 'PGK',
  'Fiji': 'FJD',
  'FJ': 'FJD',
  'Solomon Islands': 'SBD',
  'SB': 'SBD',
  'Vanuatu': 'VUV',
  'VU': 'VUV',
  'Samoa': 'WST',
  'WS': 'WST',
  'Tonga': 'TOP',
  'TO': 'TOP',
  'Kiribati': 'AUD',
  'KI': 'AUD',
  'Tuvalu': 'AUD',
  'TV': 'AUD',
  'Nauru': 'AUD',
  'NR': 'AUD',
  'Palau': 'USD',
  'PW': 'USD',
  'Micronesia': 'USD',
  'FM': 'USD',
  'Marshall Islands': 'USD',
  'MH': 'USD',
  'Greenland': 'DKK',
  'GL': 'DKK',
  'Faroe Islands': 'DKK',
  'FO': 'DKK',
  'Bermuda': 'BMD',
  'BM': 'BMD',
  'Cayman Islands': 'KYD',
  'KY': 'KYD',
  'British Virgin Islands': 'USD',
  'VG': 'USD',
  'Turks and Caicos': 'USD',
  'TC': 'USD',
  'Anguilla': 'XCD',
  'AI': 'XCD',
  'Antigua and Barbuda': 'XCD',
  'AG': 'XCD',
  'Dominica': 'XCD',
  'DM': 'XCD',
  'Grenada': 'XCD',
  'GD': 'XCD',
  'Saint Kitts and Nevis': 'XCD',
  'KN': 'XCD',
  'Saint Lucia': 'XCD',
  'LC': 'XCD',
  'Saint Vincent and the Grenadines': 'XCD',
  'VC': 'XCD',
  'Montserrat': 'XCD',
  'MS': 'XCD',
  'Barbados': 'BBD',
  'BB': 'BBD',
  'Trinidad and Tobago': 'TTD',
  'TT': 'TTD',
  'Bahamas': 'BSD',
  'BS': 'BSD',
  'Jamaica': 'JMD',
  'JM': 'JMD',
  'Haiti': 'HTG',
  'HT': 'HTG',
  'Dominican Republic': 'DOP',
  'DO': 'DOP',
  'Cuba': 'CUP',
  'CU': 'CUP',
  'Puerto Rico': 'USD',
  'PR': 'USD',
  'US Virgin Islands': 'USD',
  'VI': 'USD',
  'Guam': 'USD',
  'GU': 'USD',
  'American Samoa': 'USD',
  'AS': 'USD',
  'Northern Mariana Islands': 'USD',
  'MP': 'USD',
  'Aruba': 'AWG',
  'AW': 'AWG',
  'Curaçao': 'ANG',
  'CW': 'ANG',
  'Sint Maarten': 'ANG',
  'SX': 'ANG',
  'Bonaire': 'USD',
  'BQ': 'USD',
  'Sint Eustatius': 'USD',
  'BQ': 'USD',
  'Saba': 'USD',
  'BQ': 'USD',
  'Suriname': 'SRD',
  'SR': 'SRD',
  'Guyana': 'GYD',
  'GY': 'GYD',
  'French Guiana': 'EUR',
  'GF': 'EUR',
  'Martinique': 'EUR',
  'MQ': 'EUR',
  'Guadeloupe': 'EUR',
  'GP': 'EUR',
  'Saint Martin': 'EUR',
  'MF': 'EUR',
  'Saint Barthelemy': 'EUR',
  'BL': 'EUR',
  'Reunion': 'EUR',
  'RE': 'EUR',
  'Mayotte': 'EUR',
  'YT': 'EUR',
  'New Caledonia': 'XPF',
  'NC': 'XPF',
  'French Polynesia': 'XPF',
  'PF': 'XPF',
  'Wallis and Futuna': 'XPF',
  'WF': 'XPF',
  'Saint Pierre and Miquelon': 'EUR',
  'PM': 'EUR',
  'Saint Helena': 'SHP',
  'SH': 'SHP',
  'Falkland Islands': 'FKP',
  'FK': 'FKP',
  'Gibraltar': 'GIP',
  'GI': 'GIP',
  'Isle of Man': 'GBP',
  'IM': 'GBP',
  'Jersey': 'GBP',
  'JE': 'GBP',
  'Guernsey': 'GBP',
  'GG': 'GBP',
  'Andorra': 'EUR',
  'AD': 'EUR',
  'Liechtenstein': 'CHF',
  'LI': 'CHF',
  'Monaco': 'EUR',
  'MC': 'EUR',
  'San Marino': 'EUR',
  'SM': 'EUR',
  'Vatican City': 'EUR',
  'VA': 'EUR',
};

// Supported currencies by MPGS and your system
const supportedCurrencies = ['USD', 'GBP', 'CAD', 'AUD', 'PKR', 'AED', 'EUR', 'SAR'];

/**
 * Get currency code from country name
 * @param {string} country - Country name or code
 * @returns {string} - Currency code (defaults to PKR if not found or not supported)
 */
function getCurrencyFromCountry(country) {
  if (!country) return 'PKR';
  
  // Try exact match first
  const currency = countryCurrencyMap[country];
  if (currency && supportedCurrencies.includes(currency)) {
    return currency;
  }
  
  // Try case-insensitive match
  const lowerCountry = country.toLowerCase();
  for (const [key, value] of Object.entries(countryCurrencyMap)) {
    if (key.toLowerCase() === lowerCountry && supportedCurrencies.includes(value)) {
      return value;
    }
  }
  
  // Try partial match
  for (const [key, value] of Object.entries(countryCurrencyMap)) {
    if (lowerCountry.includes(key.toLowerCase()) && supportedCurrencies.includes(value)) {
      return value;
    }
  }
  
  // Default to PKR if not found or not supported
  return 'PKR';
}

/**
 * Get all supported currencies
 * @returns {Array} - Array of supported currency codes
 */
function getSupportedCurrencies() {
  return supportedCurrencies;
}

/**
 * Get currency display name
 * @param {string} currencyCode - Currency code
 * @returns {string} - Display name
 */
function getCurrencyDisplayName(currencyCode) {
  const names = {
    'USD': 'US Dollar ($)',
    'GBP': 'British Pound (£)',
    'CAD': 'Canadian Dollar (C$)',
    'AUD': 'Australian Dollar (A$)',
    'PKR': 'Pakistani Rupee (₨)',
    'AED': 'UAE Dirham (د.إ)',
    'EUR': 'Euro (€)',
    'SAR': 'Saudi Riyal (﷼)',
  };
  return names[currencyCode] || currencyCode;
}

/**
 * Get currency symbol
 * @param {string} currencyCode - Currency code
 * @returns {string} - Currency symbol
 */
function getCurrencySymbol(currencyCode) {
  const symbols = {
    'USD': '$',
    'GBP': '£',
    'CAD': 'C$',
    'AUD': 'A$',
    'PKR': '₨',
    'AED': 'د.إ',
    'EUR': '€',
    'SAR': '﷼',
  };
  return symbols[currencyCode] || currencyCode;
}

module.exports = {
  getCurrencyFromCountry,
  getSupportedCurrencies,
  getCurrencyDisplayName,
  getCurrencySymbol,
  countryCurrencyMap,
  supportedCurrencies
};
